/**
 * This class is generated by jOOQ
 */
package thing.jooq.tables.pojos;


import com.google.gson.JsonElement;

import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestTable implements Serializable {

    private static final long serialVersionUID = 615073928;

    private final JsonElement jsonColumn;

    public TestTable(TestTable value) {
        this.jsonColumn = value.jsonColumn;
    }

    public TestTable(
        JsonElement jsonColumn
    ) {
        this.jsonColumn = jsonColumn;
    }

    public JsonElement getJsonColumn() {
        return this.jsonColumn;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("TestTable (");

        sb.append(jsonColumn);

        sb.append(")");
        return sb.toString();
    }
}
