/**
 * This class is generated by jOOQ
 */
package thing.jooq;


import javax.annotation.Generated;

import thing.jooq.tables.TestTable;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.test_table</code>.
     */
    public static final TestTable TEST_TABLE = thing.jooq.tables.TestTable.TEST_TABLE;
}
